---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 7143, host: 7143, auto_correct: true}]
  - ["forwarded_port", {guest: 9001, host: 9001, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[onetimesecret::default]
    attributes:
